###########
# ROUTERS #
###########
http:
  routers:
  #---- Homepage Router ----#
    homepage:
      entryPoints:
        - "https"
      rule: "Host(`homepage.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare  # Add this!
      service: homepage

  #---- Portainer Router ----#
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`dev-portainer.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: portainer

  #---- Gitlab Router ----#
    gitlab:
      entryPoints:
        - "https"
      rule: "Host(`gitlab.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: gitlab

  #---- Jenkins Router ----#
    jenkins:
      entryPoints:
        - "https"
      rule: "Host(`jenkins.hikarimoon.pro`)"
      middlewares:
        - jenkins
      tls:
        certResolver: cloudflare
      service: jenkins

  #---- Immich Router ----#
    immich:
      entryPoints:
        - "https"
      rule: "Host(`immich.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: immich

  #---- SonarQube Router ----#
    sonarqube:
      entryPoints:
        - "https"
      rule: "Host(`sonarqube.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: sonarqube

  #---- TrueNas Router ----#
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: truenas

  #---- Bitwarden Router ----#
    bitwarden:
      entryPoints:
        - "https"
      rule: "Host(`bitwarden.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: bitwarden

  #---- Proxmox Router ----#
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.hikarimoon.pro`)"
      middlewares:
        - default-chain
        - proxmox
      tls:
        certResolver: cloudflare
      service: proxmox

  #---- Portfolio Router ----#
    portfolio:
      entryPoints:
        - "https"
      rule: "Host(`portfolio.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: portfolio

  #---- Pulse Router ----#
    pulse:
      entryPoints:
        - "https"
      rule: "Host(`pulse.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: pulse

  #---- SeaweedFS Master Router ----#
    seaweedfs-master:
      entryPoints:
        - "https"
      rule: "Host(`master-seaweed.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: seaweedfs-master
  
  #---- SeaweedFS Filer Router ----#
    seaweedfs-filer:
      entryPoints:
        - "https"
      rule: "Host(`filer-seaweed.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: seaweedfs-filer

  #---- Internal Uptime Kuma Router ----#
    internal-uptime-kuma:
      entryPoints:
        - "https"
      rule: "Host(`in-kuma.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: internal-uptime-kuma

  #---- External Uptime Kuma Router ----#
    external-uptime-kuma:
      entryPoints:
        - "https"
      rule: "Host(`ex-kuma.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: external-uptime-kuma

  #---- Grafana Router ----#
    grafana:
      entryPoints:
        - "https"
      rule: "Host(`grafana.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: grafana

  #---- YoutubeDL Router ----#
    youtube-dl:
      entryPoints:
        - "https"
      rule: "Host(`youtubedl.hikarimoon.pro`)"
      middlewares:
        - default-chain
      tls:
        certResolver: cloudflare
      service: youtube-dl
