############
# SERVICES #
############
http:
  services:
  #---- Homepage Service ----#
    homepage:
      loadBalancer:
        servers:
          - url: "http://dev.local:3000"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Portainer Service ----#
    portainer:
      loadBalancer:
        servers:
          - url: "https://dev.local:9443"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Gitlab Service ----#
    gitlab:
      loadBalancer:
        servers:
          - url: "http://gitlab.local:80"
        passHostHeader: true

  #---- Jenkins Service ----#
    jenkins:
      loadBalancer:
        servers:
          - url: "http://jenkins.local:8080"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Immich Service ----#
    immich:
      loadBalancer:
        servers:
          - url: "http://personal.local:2283"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- SonarQube Service ----#
    sonarqube:
      loadBalancer:
        servers:
          - url: "http://dev.local:9032"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- TrueNas Service ----#
    truenas:
      loadBalancer:
        servers:
          - url: "http://truenas.local:80"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Bitwarden Service ----#
    bitwarden:
      loadBalancer:
        servers:
          - url: "http://person.local"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Proxmox Service ----#
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.1.33:8006"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Portfolio Service ----#
    portfolio:
      loadBalancer:
        servers:
          - url: "http://dev.local:9463"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Pulse Service ----#
    pulse:
      loadBalancer:
        servers:
          - url: "http://dev.local:7655"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- SeaweedFS Master Service ----#
    seaweedfs-master:
      loadBalancer:
        servers:
          - url: "http://dev.local:9333"
        passHostHeader: true
        serversTransport: insecureTransport
  
  #---- SeaweedFS Filer Service ----#
    seaweedfs-filer:
      loadBalancer:
        servers:
          - url: "http://dev.local:8888"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Internal Uptime Kuma Service ----#
    internal-uptime-kuma:
      loadBalancer:
        servers:
          - url: "http://dev.local:3001"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- External Uptime Kuma Service ----#
    external-uptime-kuma:
      loadBalancer:
        servers:
          - url: "http://dev.local:3002"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- Grafana Service ----#
    grafana:
      loadBalancer:
        servers:
          - url: "http://dev.local:3002"
        passHostHeader: true
        serversTransport: insecureTransport

  #---- YoutubeDL Service ----#
    youtube-dl:
      loadBalancer:
        servers:
          - url: "http://personal.local:8998"
        passHostHeader: true
        serversTransport: insecureTransport
